version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: my_delivery_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
